### ISSUE TITLE
Testing enviroment

### ISSUE THREAD

**Issue by gregzhadko** [dfomin/judgebot#1]
Create a test environment with basic instructions of how to use it, so any developer can test their changes.
I would advise creating a test database + test bot.

**Comment by dfomin** [comment]
Hello, Greg, thanks for contributing judgebot.
We have test mode (-t or --test) for the bot, it allows you send any commands to the bot directly on terminal without any interaction with telegram/network etc. All you need is just create your own copy of postgres database (see src/judgebot/database/dbschema.sql) and create judgebot user manually.
Network behavior isn't supposed to be changed, so any business logic features can be implemented locally.
